### PR TITLE
Added currency cells.

### PR DESCRIPTION
**Pull request by cbh2000**
I added two currency cell styles: one with cents and one without. They're internationalized too. Values are stored internally as NSDecimalNumber to avoid precision loss.

example

internationalization

### CODE REVIEW

**Comment by ziogaschr** [comment]
You can also use something like #306 & #195 & #77 (all are the same) for achieving the same without adding a new cell type.

**Comment by cbh2000** [comment]
@ziogaschr Almost.

While adding a NSFormatter will enable currency formatting, NSNumberFormatter's currency formatting is extremely picky about the format (user can type `1 000 €` but not `1 000€` or `1 000` or `1000`). And the decimal pad keyboard doesn't have a currency symbol, so we'd have to use the standard keyboard.

If we use a decimal field for currency, you'll find it has precision issues (try typing in "8.14," it displays as "8.1400000000...1"). In the end, the user would have to create their own cell or use a text cell with a decimal pad and no formatter.

If we'd rather not add another cell type, would you be ok if I exposed the textfield delegate methods of XLFormTextFieldCell in another PR? Right now I can't override them without resorting to hacks.

**Comment by ziogaschr** [comment]
This is exactly how it works using an NSFormatter. Except that you don't have a currency symbol in the keyboard. Although from what I can see from your GIF's you have a single currency sign predefined.

simulator screen shot sep 25 2015 10 58 02
simulator screen shot sep 25 2015 10 57 53

**Comment by cbh2000** [comment]
I like @ziogaschr's PR better. :smile:

**Pull request closed without merging**
