### PR TITLE
Fix use of formatter in Info Cells

### PR DESCRIPTION
**Pull request by felix-dumit**
Currently it will not use the provided `valueFormatter` if the row is `XLFormRowDescriptorTypeInfo`.

- To reproduce this issue I added an extra row to the `FormattersViewController` using `NSByteCountFormatter` ea96fe9
- To fix I made `XLFormRowDescriptor` conform  to `XLFormOptionObject` so it will format using the provided formatter if available.  cebfbecc6f3c44cc0997fd61b1824f1d792d1c9b

### CODE REVIEW

**Comment by mats-claassen** [comment]
I am not sure that it is necessary that XLFormRowDescriptor conforms to XLFormOptionsObject. It should work to put an `if (self.rowDescriptor.valueFormatter)` inside `valueDisplayText` of XLFormSelectorCell. What do you think of that?

**Comment by felix-dumit** [comment]
Actually now that I'm looking at it, wouldn't it be possible to just replace
```objc
return [self.rowDescriptor.value displayText];
```
With:
```objc
return self.rowDescriptor.displayTextValue;
```

Since `displayTextValue` calls into `value.displayText` when there is no formatter.
What do you think?
I can squash these last commits as well if you want to merge like this.

**Comment by mats-claassen** [comment]
Yeah looks fine. I can squash and merge it from here unless you want to do it manually.

**Comment by felix-dumit** [comment]
@mats-claassen Just pushed it. Thanks!

**Pull request merged**
