### PR TITLE
Cell height api

### PR DESCRIPTION
**Pull request by jpmhouston**
Improvements to XLFormDescriptorCell protocol for row heights & self-sizing, addresses #721

### CODE REVIEW

**Comment by jpmhouston** [comment]
Perhaps the height and heightEstimate methods are kinda awkward. I suspect it would be better to have the methods return the height value instead of a bool, with a special value to mean "ignore, use the default".

I'll post another comment later making this more clear.

**Comment by jpmhouston** [comment]
I suspect these delegate methods would make more sense, negating the `BOOL` result and `inout` height parameter, and reordering parameters for consistency with other delegate methods:

    +(CGFloat)formDescriptorCellHeightWithFormController:(XLFormViewController *)controller default:(CGFloat)defaultHeight forRowDescriptor:(XLFormRowDescriptor *)rowDescriptor;
    +(CGFloat)formDescriptorCellHeightEstimateWithFormController:(XLFormViewController *)controller default:(CGFloat)defaultHeightEstimate forRowDescriptor:(XLFormRowDescriptor *)rowDescriptor;
    +(BOOL)formDescriptorCellPrefersSelfSizingWithFormController:(XLFormViewController *)controller forRowDescriptor:(XLFormRowDescriptor *)rowDescriptor;

also with this new constant in the header, which when returned tells `XLFormViewController` to choose what height value to return to the `UITableView` (equivalent to returning `NO` for the methods currently defined in this PR):

    extern CGFloat XLFormUnspecifiedCellHeight; // return from formDescriptorCellHeight methods
                                                // to tell view controller to use its default

Note, this special value is necessary because the `defaultHeight`/`defaultHeightEstimate` value passed to the delegate methods never equals `UITableViewAutomaticDimension`, but always a valid height value (at worst 0), so as not to burden the cell author with details of `UITableView`. For the view controller to be able to choose what value, including `Automatic`, to return the table view, these delegate methods really need a way to return a "null" result. The view controller would need to ensure never to return `Unspecified` back to the table view.

**Comment by mats-claassen** [comment]
Hi @jpmhouston , as we have moved `updateFormRow` from the `willDisplayCell` method to `cellForRowAtIndexPath` this pull request is a bit outdated.

It is an interesting feature but I would prefer to implement it a bit more like it is in Eureka where we use blocks to call for the height of a cell. And is it necessary to add a function for the estimated height of a cell?

Also, for autoresizing, [this commit](https://github.com/xmartlabs/Eureka/commit/acc642ec500f34b15ed26d7fe94f2f8e3b8aa869) solves that for TextView in Eureka.

**Comment by mats-claassen** [comment]
I have merged a version with a height property in XLFormRowDescriptor. 
This solves only part of what you propose as self-sizing is not supported.

Thank you for your pull request anyway as it did give me some ideas for this implementation.

**Comment by jpmhouston** [comment]
Cool. FWIW I'll soon make my fork in sync with the recent upstream changes you mentioned, and might try to keep it in sync going forward. But understandable if you wish to close this issue.

**Pull request closed without merging**
