### PR TITLE
Fix Ipad layout on iOS 9.0

### PR DESCRIPTION
**Pull request by jakubprusa**
Fix layout in both rotations, portrait and landscape 

Mentioned in these issues: #627 #554

### CODE REVIEW

**Comment by jakubprusa** [comment]
I tried to run test on own pc and all tests passed. Can you please explain me where is the error?

**Comment by bmichotte** [comment]
What if you change your `if` by

```objc
if([self.tableView respondsToSelector:@selector(cellLayoutMarginsFollowReadableWidth))
{
    self.tableView.cellLayoutMarginsFollowReadableWidth = NO;
}

**Comment by jakubprusa** [comment]
Hi i can try it, but when i'am testing on my localhost i had same results as for SYSTEM_VERSION_GREATER_THAN_OR_EQUAL_TO.

**Comment by jakubprusa** [comment]
Finished with same result, any idea why?

**Comment by bmichotte** [comment]
mhhh, ok, this is because the installed xcode version on travis is a 6, so it compiles with ios 8.4 as target and therefore does not find the property at compile time.

The tests should pass using ```performSelect:```. Unfortunately, this property takes a `BOOL`, so the only way is either with 
```#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 90000```
or with 
```objc
NSMethodSignature* signature = [[self.tableView class] instanceMethodSignatureForSelector:@selector(setCellLayoutMarginsFollowReadableWidth:)];
NSInvocation* invocation = [NSInvocation invocationWithMethodSignature:signature];
[invocation setTarget:self.tableView];
[invocation setSelector:@selector(setCellLayoutMarginsFollowReadableWidth:)];
        
BOOL boolValue = NO;
[invocation setArgument:&boolValue atIndex: 2];
[invocation invoke];
```

**Comment by jakubprusa** [comment]
Wow, i see this pattern for first time. Should i make another commit with this code or do you prefer some another way? 

Or you can update build script for xcode 7. I don't if you just select another virtual machine with newer xcode and that's it or you need to do something more. But at least i consider to update travis CI to newer version.

**Comment by bmichotte** [comment]
(i'm not related to xmartlabs, I just really wish this issue to be fixed ^^)
You can add `osx_image: xcode7` on the .travis.yml file but I don't know if the vm is stable

@mtnbarreto / @mats-claassen could you please check this PR please ?

**Comment by jakubprusa** [comment]
You can make change directly to your dowloaded pod and wait for it, you want it asap :D 
I will try your remake of code and will se what happend :)

**Comment by jakubprusa** [comment]
@mtnbarreto / @mats-claassen ping? :)

**Comment by mtnbarreto** [comment]
@bmichotte @jakubprusa Thanks for helping me with this!

**Comment by bmichotte** [comment]
@mtnbarreto thanks for the merge !

(maybe it's time to consider `osx_image: xcode7` in .travis.yml btw :)

**Comment by mtnbarreto** [comment]
@bmichotte sure! Seems current Xcode version sdk does not even has `cellLayoutMarginsFollowReadableWidth ` method.

**Pull request closed without merging**
