### PR TITLE
Support for NSFormatter

### PR DESCRIPTION
**Pull request by fwhenin**
Saw this about 3 months ago in one of the pull requests by @bhirt-bpl , there were merge conflicts that might be too late now to deal with, so I moved them to the latest commit. hopefully this makes it in

### CODE REVIEW

**Comment by ziogaschr** [comment]
+1

I would like to have this merged in master as soon as possible.
Let me know if I can help in any way.

Nice work @fwhenin

**Comment by ziogaschr** [comment]
I have tested the code in my project and it works fine

**Comment by ziogaschr** [comment]
@fwhenin I have tried to edit a formatted phone number by removing a digit in the middle of the number.
For example in `(800) 222-1222`, I have removed the `1` and the number became `(800) 222-222`.
The thing is that the cursor position wasn't maintained and it moved to the end of the string, that confuses the user and he has to move again the cursor to the same position.

I was able to handle that in `(BOOL)textField:(UITextField *)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString *)string` in *my old code* but not now in XLForms as `UIControlEventEditingChanged` is being called after a string has changed.

I am trying to find a solution to help you, but do you know how the code can handle that?

**Comment by ziogaschr** [comment]
Any plans on merging this pull request? Thanks

**Comment by emablekos** [comment]
This would be an awesome add!

**Comment by jamesestmoi** [comment]
This would be the final touch to this almost perfect form library

**Comment by macecchi** [comment]
+1 :+1:

**Comment by ngheungyu** [comment]
Guys, it crashed on brand new repo clone .... #808 Please help

**Pull request closed without merging**
